# -*- coding: utf-8 -*-
"""MultipleLinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgjpPcODe3QuK7SNYtnqHM1obMMoo0MF
"""

from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

plt.plot(X,y,'*')

df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})
df

df.shape

fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train,y_train)

y_pred = lr.predict(X_test)

print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

"""# **Multiple Linear Regression**"""

import numpy as np
from sklearn.datasets import load_diabetes

X,y = load_diabetes(return_X_y=True)

X

X.shape

y.shape

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

print(X_train.shape)
print(X_test.shape)

from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)

from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

reg.coef_

reg.intercept_

"""# ***Making our own Linear Regression Class***"""

class MeraLR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

lr = MeraLR()

lr.fit(X_train,y_train)

X_train.shape

np.insert(X_train,0,1,axis=1).shape

y_pred = lr.predict(X_test)

r2_score(y_test,y_pred)

lr.coef_

lr.intercept_

